name: My First Node.js Application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix: 
        node-version: ['18.x']

    steps:
      - name: Check out Repository 
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Fix Babel dependencies
        working-directory: ./frontend
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Create frontend build
        working-directory: ./frontend
        run: npm run build

      - name: Upload the Artifact
        run: aws s3 cp ./frontend/build s3://jokeappfrontend --recursive
